version: "3.9"
services:
  backend:
    build: .
    ports:
      - 8001:8001
    volumes:
      - .:/app
    depends_on:
      - mongo
      - rabbitmq
      - redis
      - mongo-interface
    networks:
      - micro-adopt-me

  mongo:
    image: mongo
    restart: always
    command: mongod --port 27010
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-db-user:/data/db
    ports:
      - 27010:27010
    networks:
      - micro-adopt-me

  rabbitmq:
    image: rabbitmq:3.9-management
    ports:
      - 5001:15672
      - 5002:5672
    networks:
      - micro-adopt-me

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - micro-adopt-me

  mongo-interface:
    image: mongo-express:latest
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_PORT=27010
      - ME_CONFIG_MONGODB_SERVER=mongo
    networks:
      - micro-adopt-me
    depends_on:
      - mongo

volumes:
  mongo-db-user:

networks:
  micro-adopt-me:
    driver: bridge
